---
### init docker swarm on leader node
- name: init swarm mode on master
  when: "'leader' in group_names"
  block:
  - name: Docker login
    command: "docker login {{ docker_registry_host }} -u {{ docker_registry_user }} -p {{ docker_registry_pass }}"
    # check_mode: "true"
  # -----
  - name: Docker Swarm init
    command: "docker swarm init --advertise-addr {{}}"
    # check_mode: "true"
  # -----
  - name: Get docker join token for manager node
    register: reg_docker_join_token_manager
    changed_when: reg_docker_join_token_manager.rc >= 2
    command: "docker swarm join-token manager"
  # -----
  - name: Get docker join token for worker node
    register: reg_docker_join_token_worker
    changed_when: reg_docker_join_token_worker.rc >= 2
    command: "docker swarm join-token worker"
  # -----
  - name: Save docker join token for manager to fact
    set_fact:
      fact_docker_swarm_token_manager: "{{ reg_docker_join_token_manager['stdout_lines'][2] | trim }}"
      cacheable: yes
  # -----
  - name: Save docker join token for worker to fact
    set_fact:
      fact_docker_swarm_token_worker: "{{ reg_docker_join_token_worker['stdout_lines'][2] | trim }}"
      cacheable: yes
  rescue:
  - name: Tasks name cause error
    debug:
      var: ansible_failed_task.name